# Parte 1

In [1]:
!nvidia-smi

Thu Mar 19 12:03:34 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch

In [3]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

In [4]:
device

device(type='cuda')

In [6]:
x = torch.randn(4, 4)

y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
# z = z.numpy() # not possible because numpy cannot handle GPU tensors
# move to CPU again
#z.to("cpu")       # ``.to`` can also change dtype together!
# z = z.numpy()

In [ ]:
z

tensor([[ 1.7603,  2.4678, -0.7855,  0.0469],
        [-0.5497,  2.2194,  2.3745,  1.7045],
        [ 2.0789, -1.3413,  1.0005,  1.5061],
        [-0.3249,  1.2915,  0.2511,  0.9315]], device='cuda:0')

In [ ]:
z.to('cpu').numpy()

array([[ 1.7602789 ,  2.4678152 , -0.7854507 ,  0.04691607],
       [-0.5496701 ,  2.2194352 ,  2.3744528 ,  1.7045219 ],
       [ 2.0789032 , -1.3412564 ,  1.0005094 ,  1.5060668 ],
       [-0.32494164,  1.2915394 ,  0.2510937 ,  0.93153477]],
      dtype=float32)

# Parte 2

Regressao

In [ ]:
import torch

x_data = torch.tensor([[1.0], [2.0], [3.0]])
y_data = torch.tensor([[2.0], [4.0], [6.0]])

class Model(torch.nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.linear = torch.nn.Linear(1,1)
  def forward(self, x):
    y_pred = self.linear(x)
    return y_pred


In [21]:
model = Model()

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(500):
  y_pred = model(x_data)

  loss = criterion(y_pred, y_data)
  optimizer.zero_grad()

  loss.backward()
  optimizer.step()
  if epoch%50 == 0:
    print(f"Época {epoch} | Loss {loss.data}")


Época 0 | Loss 51.11134338378906
Época 50 | Loss 0.001038465998135507
Época 100 | Loss 9.112153202295303e-05
Época 150 | Loss 7.995676241989713e-06
Época 200 | Loss 7.016215022304095e-07
Época 250 | Loss 6.161487675626631e-08
Época 300 | Loss 5.402777336627196e-09
Época 350 | Loss 4.712698564723894e-10
Época 400 | Loss 4.069988790433854e-11
Época 450 | Loss 3.48639628451608e-12


Classificacao binária

In [47]:
import torch

x_data = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
y_data = torch.tensor([[0.0], [0.0], [1.0], [1.0], [1.0]])

class Model(torch.nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.linear = torch.nn.Linear(1,1)
    self.Sigmoid = torch.nn.Sigmoid()
  def forward(self, x):
    sigma = self.Sigmoid
    y_pred = sigma( self.linear(x) )
    return y_pred
  def predict(self, x):
    return 1 if self.forward(x) > 0.5 else 0

In [48]:
model = Model()

#criterion = torch.nn.MSELoss()
criterion = torch.nn.BCELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(500):
  y_pred = model(x_data)

  loss = criterion(y_pred, y_data)
  optimizer.zero_grad()

  loss.backward()
  optimizer.step()
  if epoch%50 == 0:
    print(f"Época {epoch} | Loss {loss.data}")


Época 0 | Loss 1.2783081531524658
Época 50 | Loss 0.4975721836090088
Época 100 | Loss 0.41696906089782715
Época 150 | Loss 0.3593621253967285
Época 200 | Loss 0.3170575499534607
Época 250 | Loss 0.2850089371204376
Época 300 | Loss 0.25999560952186584
Época 350 | Loss 0.23994776606559753
Época 400 | Loss 0.2235061228275299
Época 450 | Loss 0.20975427329540253


In [45]:
model.forward(torch.tensor([1.0]))

tensor([0.1177], grad_fn=<SigmoidBackward0>)

In [51]:
model.predict(torch.tensor([5.0]))

1

---

In [54]:
import torch

x_data = torch.tensor([[2.1, 0.1],
                       [4.2, 0.8],
                       [3.1, 0.9],
                       [3.3, 0.2]])
y_data = torch.tensor([[0.0], [1.0], [0.0], [1.0]])

#############################################################

class Model(torch.nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.linear = torch.nn.Linear(2,1)
    self.Sigmoid = torch.nn.Sigmoid()
  def forward(self, x):
    sigma = self.Sigmoid
    y_pred = sigma( self.linear(x) )
    return y_pred
  def predict(self, x):
    return 1 if self.forward(x) > 0.5 else 0

#############################################################
model = Model()


#criterion = torch.nn.MSELoss()
criterion = torch.nn.BCELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(500):
  y_pred = model(x_data)

  loss = criterion(y_pred, y_data)
  optimizer.zero_grad()

  loss.backward()
  optimizer.step()
  if epoch%50 == 0:
    print(f"Época {epoch} | Loss {loss.data}")


Época 0 | Loss 0.7095865607261658
Época 50 | Loss 0.6445403099060059
Época 100 | Loss 0.6058554649353027
Época 150 | Loss 0.5704358816146851
Época 200 | Loss 0.5379894971847534
Época 250 | Loss 0.5082430839538574
Época 300 | Loss 0.48094385862350464
Época 350 | Loss 0.45586007833480835
Época 400 | Loss 0.4327808618545532
Época 450 | Loss 0.4115152657032013


Porta XOR

<img src="https://embarcados.com.br/wp-content/uploads/2015/11/xor-11-850x308.jpg.webp" width="50%">

#TODO arrumar isso

In [75]:
import torch

x_data = torch.tensor([[0, 0],
                       [0, 1],
                       [1, 0],
                       [1, 1]], dtype=torch.float)

y_data = torch.tensor([[0],
                       [1],
                       [1],
                       [0]], dtype=torch.float)

#############################################################

class Model(torch.nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    self.l1 = torch.nn.Linear(2,4)
    self.l2 = torch.nn.Linear(4,3)
    self.l3 = torch.nn.Linear(3,1)
    self.Sigmoid = torch.nn.Sigmoid()
  def forward(self, x):
    sigma = self.Sigmoid
    out1 = sigma( self.l1(x) )
    out2 = sigma( self.l2(out1) )
    y_pred = sigma( self.l3(out2) )
    return y_pred
  def predict(self, x):
    return 1 if self.forward(x) > 0.5 else 0

#############################################################
model = Model()

criterion = torch.nn.BCELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

for epoch in range(500):
  y_pred = model(x_data)

  loss = criterion(y_pred, y_data)
  optimizer.zero_grad()

  loss.backward()
  optimizer.step()
  if epoch%50 == 0:
    print(f"Época {epoch} | Loss {loss.data}")


Época 0 | Loss 0.715726375579834
Época 50 | Loss 0.7074158787727356
Época 100 | Loss 0.7021454572677612
Época 150 | Loss 0.6988140940666199
Época 200 | Loss 0.696712851524353
Época 250 | Loss 0.6953890919685364
Época 300 | Loss 0.6945558190345764
Época 350 | Loss 0.6940315961837769
Época 400 | Loss 0.6937018632888794
Época 450 | Loss 0.693494439125061


In [72]:
for x in x_data:
  print(model.predict(x))

1
1
0
0
