In [1]:
import torch

### Tensores não inicializados
Podemos criar um tensor vazio com a função torch.empty(). O tensor resultante terá os valores que já existiam na memória naquele momento.

In [2]:
# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([0.])
tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


Para não ter lixo de execução podemos zerar as variáveis

In [3]:
torch.zeros(1,2,2)

tensor([[[0., 0.],
         [0., 0.]]])

### Tensores Aleatórios
Podemos criar um tensor preenchido com valores aleatórios usando torch.rand(). Os valores gerados estão no intervalo [0, 1].

In [4]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.0257, 0.8357, 0.0472],
        [0.4059, 0.6965, 0.7743],
        [0.8409, 0.3457, 0.4743],
        [0.0462, 0.0086, 0.7110],
        [0.5988, 0.4919, 0.3163]])


### Tensores Preenchidos com Zeros ou Uns
Podemos criar um tensor preenchido com zeros usando torch.zeros() ou preenchido com uns usando torch.ones().

In [5]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### Verificando o tamanho e tipo do Tensor
Podemos verificar o tamanho do tensor usando a propriedade .size(). Para verificar o tipo do tensor, podemos usar a propriedade .dtype.

In [7]:
# check size
print(x.size())

# check data type
print(x.dtype)

torch.Size([5, 3])
torch.float32


### Variáveis e Gradientes
Podemos especificar se queremos que o PyTorch calcule os gradientes para um tensor. Isso é necessário quando estamos treinando um modelo de aprendizado de máquina. Para especificar isso, podemos usar o argumento requires_grad=True.

In [8]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
w = torch.tensor([5.5, 3], requires_grad=True)

Exemplo de uso

In [9]:
aux = [2, 3]
x = torch.tensor(aux, dtype=torch.float32)

In [10]:
x

tensor([2., 3.])

In [11]:
w

tensor([5.5000, 3.0000], requires_grad=True)

In [12]:
sigma = torch.nn.Sigmoid()

In [13]:
y_hat = sigma(w @ x)

In [14]:
y_hat

tensor(1., grad_fn=<SigmoidBackward0>)

In [15]:
y = 0.0

Loss = 0.5*(y_hat - y)**2
Loss

tensor(0.5000, grad_fn=<MulBackward0>)

### Operações com Tensores
Podemos realizar operações elementares com tensores, como adição, subtração, multiplicação e divisão

In [16]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)

# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

### Fatiamento de Tensores
Podemos fatiar um tensor para obter um subconjunto dele. O fatiamento funciona de forma semelhante à fatia de uma lista ou matriz.

In [17]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.8740, 0.2417, 0.8942],
        [0.3135, 0.8225, 0.7824],
        [0.1135, 0.5129, 0.0136],
        [0.5474, 0.0693, 0.7806],
        [0.0210, 0.9311, 0.5377]])
tensor([0.8740, 0.3135, 0.1135, 0.5474, 0.0210])
tensor([0.3135, 0.8225, 0.7824])
tensor(0.8225)
0.8224724531173706


### Redimensionamento de Tensores
Podemos redimensionar um tensor usando a função .view(). O novo tensor terá a mesma quantidade de elementos que o tensor original.

In [18]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [28]:
x

tensor([[ 0.5638, -0.9674, -0.9924, -0.1096],
        [-0.7058,  0.4718,  0.2112,  1.5972],
        [ 1.4661,  0.5636,  0.1578, -1.2150],
        [-0.8164,  1.4320,  1.0398, -0.7521]])

In [29]:
x.view(16)

tensor([ 0.5638, -0.9674, -0.9924, -0.1096, -0.7058,  0.4718,  0.2112,  1.5972,
         1.4661,  0.5636,  0.1578, -1.2150, -0.8164,  1.4320,  1.0398, -0.7521])

In [30]:
x.view(-1)

tensor([ 0.5638, -0.9674, -0.9924, -0.1096, -0.7058,  0.4718,  0.2112,  1.5972,
         1.4661,  0.5636,  0.1578, -1.2150, -0.8164,  1.4320,  1.0398, -0.7521])

In [31]:
x.view(-1,8) # -1 ele calcula automático!

tensor([[ 0.5638, -0.9674, -0.9924, -0.1096, -0.7058,  0.4718,  0.2112,  1.5972],
        [ 1.4661,  0.5636,  0.1578, -1.2150, -0.8164,  1.4320,  1.0398, -0.7521]])

### Conversão entre PyTorch e NumPy
Podemos converter facilmente um tensor PyTorch em um array NumPy usando a função .numpy(). Da mesma forma, podemos converter um array NumPy em um tensor PyTorch usando a função torch.from_numpy().

In [24]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### Usando a GPU
Se o PyTorch estiver instalado com suporte a GPU, podemos mover tensores para a GPU usando .to('cuda'). Podemos verificar se o suporte a GPU está disponível usando torch.cuda.is_available().

In [25]:
!nvidia-smi

Thu Mar 19 08:57:43 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 573.48                 Driver Version: 573.48         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA T400 4GB              WDDM  |   00000000:01:00.0  On |                  N/A |
| 38%   46C    P8            N/A  /   31W |     508MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [26]:
device = torch.device('cuda')

In [27]:
device

device(type='cuda')

In [35]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

In [29]:
device

device(type='cuda')

In [ ]:
x = torch.randn(4, 4)

y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
# z = z.numpy() # not possible because numpy cannot handle GPU tensors
# move to CPU again
z.to("cpu")       # ``.to`` can also change dtype together!
# z = z.numpy()

In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

## Autograd

Esse código mostra exemplos de como usar o PyTorch com a funcionalidade de diferenciação automática fornecida pelo pacote autograd.

O código começa criando um tensor x de forma aleatória e com um sinalizador `requires_grad=True` que permite rastrear todas as operações executadas sobre esse tensor. Então, é criado outro tensor y que é resultado de uma operação com o tensor x. Como o tensor y foi criado como resultado de uma operação, ele tem um atributo grad_fn que se refere a uma função que criou o tensor.

São realizadas mais operações com o tensor y, incluindo o cálculo dos gradientes com a função `backward()` que computa automaticamente as derivadas parciais em relação ao tensor de entrada.

O código também mostra como lidar com tensores que não rastreiam o histórico de operações e como lidar com tensores que possuem saída não escalar. Além disso, há um exemplo de como esvaziar os gradientes antes de uma nova etapa de otimização.

Por fim, o código menciona a existência de uma classe Optimizer em PyTorch que tem um método `zero_grad()` que pode ser usado para esvaziar os gradientes antes de uma nova etapa de otimização.


O pacote autograd fornece diferenciação automática para todas as operações em tensores

In [34]:
import torch

# O requires_grad = True rastreia todas as operações no tensor.
x = torch.randn(3, requires_grad=True)
y = x + 2

# y foi criado como resultado de uma operação, então ele tem um atributo grad_fn.
# grad_fn referencia uma Função que criou o Tensor
print(x) # criado pelo usuário -> grad_fn é None
print(y)
print(y.grad_fn)

# Faça mais operações em y
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([-0.4320, -1.2560, -0.0616], requires_grad=True)
tensor([1.5680, 0.7440, 1.9384], grad_fn=<AddBackward0>)
tensor([ 7.3756,  1.6606, 11.2717], grad_fn=<MulBackward0>)
tensor(6.7693, grad_fn=<MeanBackward0>)


Vamos calcular os gradientes com backpropagation
Quando terminarmos nossa computação, podemos chamar .backward() e ter todos os gradientes calculados automaticamente.
O gradiente para este tensor será acumulado no atributo .grad.
É a derivada parcial da função em relação ao tensor

In [35]:
z.backward()
print(x.grad) # dz/dx

# Em geral, torch.autograd é um mecanismo para computar o produto vetor-Jacobiano
# Ele computa derivadas parciais enquanto aplica a regra da cadeia

tensor([3.1359, 1.4880, 3.8767])


Modelo com saída não escalar:
Se um Tensor não é escalar (mais de um elemento), precisamos especificar argumentos para backward ()
especificar um argumento de gradiente que é um tensor de forma correspondente.
necessário para o produto vetor-Jacobiano

In [36]:
x = torch.randn(3, requires_grad=True)

y = x * 2
for _ in range(10):
    y = y * 2

print(y)
print(y.shape)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
y.backward(v)
print(x.grad)

tensor([ 7056.0703,   942.2576, -2229.3447], grad_fn=<MulBackward0>)
torch.Size([3])
tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


Pare um tensor de rastrear a história:
Por exemplo, durante nosso loop de treinamento, quando queremos atualizar nossos pesos
então esta operação de atualização não deve fazer parte do cálculo do gradiente
- x.requires_grad_(False)
- x.detach()
- wrap in 'with torch.no_grad():'

In [37]:
# .requires_grad_(...) muda uma flag existente inplace.
a = torch.randn(2, 2)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [38]:
# .detach(): obtenha um novo Tensor com o mesmo conteúdo, mas sem cálculo de gradiente:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
b = a.detach()
print(b.requires_grad)

True
False


In [39]:
# wrap in 'with torch.no_grad():'
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
False


 backward() acumula o gradiente para este tensor no atributo .grad.
* Precisamos ter cuidado durante a otimização!

Use .zero_() para esvaziar os gradientes antes de uma nova etapa de otimização!

In [40]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    # apenas um exemplo simples
    model_output = (weights*3).sum()
    model_output.backward()

    print(weights.grad)
    # otimizar o modelo, ou seja, ajustar os pesos ...
    with torch.no_grad():
        weights -= 0.1 * weights.grad

    # isso é importante! Isso afeta os pesos e a saída final
    weights.grad.zero_()

print(weights)
print(model_output)

# Otimizador tem um método zero_grad ()
# optimizer = torch.optim.SGD([weights], lr=0.1)
# Durante o treinamento:
# optimizer.step()
# optimizer.zero_grad()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([0.1000, 0.1000, 0.1000, 0.1000], requires_grad=True)
tensor(4.8000, grad_fn=<SumBackward0>)


## Backpropagation

O código é um exemplo simples de otimização de parâmetros usando PyTorch. Ele segue os seguintes passos:

1. Inicializa os tensores x, y e w.
2. Define o tensor w como o parâmetro que será otimizado, usando o argumento requires_grad=True.
3. Realiza a forward pass para calcular a perda (loss) com base na previsão (y_predicted) e na saída esperada (y).
4. Realiza a backward pass para calcular os gradientes da perda em relação aos parâmetros.
5. Atualiza os pesos (w) usando um otimizador com base nos gradientes calculados.
6. Zera os gradientes antes de realizar a próxima iteração do processo de otimização.

O código também imprime o valor da perda e do gradiente para o parâmetro w a cada iteração.

In [41]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

# Este é o parâmetro que queremos otimizar -> requires_grad=True
w = torch.tensor(1.0, requires_grad=True)

# forward pass para calcular a perda
y_predicted = w * x
loss = (y_predicted - y)**2
print(loss)


tensor(1., grad_fn=<PowBackward0>)


$$\frac{\partial \mathcal{Loss}}{\partial w} = 2 x (wx-y)$$ 

In [42]:
# backward pass para calcular o gradiente dLoss/dw
loss.backward()
print(w.grad)

tensor(-2.)


In [43]:
# atualiza os pesos
# próxima forward e backward pass...

# continua otimizando:
# atualiza os pesos, esta operação não deve fazer parte do grafo computacional
with torch.no_grad():
    w -= 0.01 * w.grad
# não se esqueça de zerar os gradientes
w.grad.zero_()

tensor(0.)

In [44]:
w

tensor(1.0200, requires_grad=True)

## Gradiente descendente

### Computar cada passo manualmente

O primeiro bloco de código implementa uma regressão linear em numpy, onde a relação entre as entradas X e saídas Y é f = 2x. A implementação envolve o cálculo da saída do modelo (forward), da função de perda (loss) e do gradiente da função de perda em relação aos pesos (gradient). O treinamento é realizado iterativamente atualizando os pesos com base nos gradientes calculados.

In [45]:
import numpy as np

# Regressão linear
# f = w * x

# aqui: f = 2 * x
X = np.array([1, 2, 3, 4], dtype=np.float32)
Y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

# saída do modelo
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

# J = MSE = 1/N * (w*x - y)**2
# dJ/dw = 1/N * 2x(w*x - y)
def gradient(x, y, y_pred):
    return np.dot(2*x, y_pred - y).mean()

print(f'Predição antes do treinamento: f(5) = {forward(5):.3f}')

# Treinamento
learning_rate = 0.01
n_iters = 20

for epoch in range(n_iters):
    # predict = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calculate gradients
    dw = gradient(X, Y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 2 == 0:
        print(f'época {epoch+1}: w = {w:.3f}, loss = {l:.8f}')

print(f'Predição após o treinamento: f(5) = {forward(5):.3f}')


Predição antes do treinamento: f(5) = 0.000
época 1: w = 1.200, loss = 30.00000000
época 3: w = 1.872, loss = 0.76800019
época 5: w = 1.980, loss = 0.01966083
época 7: w = 1.997, loss = 0.00050332
época 9: w = 1.999, loss = 0.00001288
época 11: w = 2.000, loss = 0.00000033
época 13: w = 2.000, loss = 0.00000001
época 15: w = 2.000, loss = 0.00000000
época 17: w = 2.000, loss = 0.00000000
época 19: w = 2.000, loss = 0.00000000
Predição após o treinamento: f(5) = 10.000


### Autograd

O segundo bloco de código é uma implementação semelhante de regressão linear, mas usando o pacote PyTorch. Mais uma vez, a relação entre as entradas X e saídas Y é f = 2x. No entanto, o PyTorch simplifica muito o processo de treinamento em relação à implementação manual em numpy. O cálculo da saída do modelo, da função de perda e do gradiente são feitos automaticamente com o recurso de autograd. As atualizações de peso são feitas com o auxílio do otimizador de descida de gradiente em vez de atualizações manuais.


In [46]:
import torch

# Regressão Linear
# f = w * x

# aqui: f = 2 * x
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# saída do modelo
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y)**2).mean()

print(f'Previsão antes do treinamento: f(5) = {forward(5).item():.3f}')

# Treinamento
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # previsão = forward pass
    y_pred = forward(X)

    # loss
    l = loss(Y, y_pred)

    # calcular gradientes = backward pass
    l.backward()

    # atualizar pesos
    with torch.no_grad():
        w -= learning_rate * w.grad

    # zerar os gradientes após a atualização
    w.grad.zero_()

    if epoch % 10 == 0:
        print(f'epoch {epoch+1}: w = {w.item():.3f}, loss = {l.item():.8f}')

print(f'Previsão após o treinamento: f(5) = {forward(5).item():.3f}')


Previsão antes do treinamento: f(5) = 0.000
epoch 1: w = 0.300, loss = 30.00000000
epoch 11: w = 1.665, loss = 1.16278565
epoch 21: w = 1.934, loss = 0.04506890
epoch 31: w = 1.987, loss = 0.00174685
epoch 41: w = 1.997, loss = 0.00006770
epoch 51: w = 1.999, loss = 0.00000262
epoch 61: w = 2.000, loss = 0.00000010
epoch 71: w = 2.000, loss = 0.00000000
epoch 81: w = 2.000, loss = 0.00000000
epoch 91: w = 2.000, loss = 0.00000000
Previsão após o treinamento: f(5) = 10.000
